var data = [
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Total",
      "Year": 2018,
      "Region": "ACT",
      "Sex": "Total",
      "Age": "Year 6",
      "Percent": 82.88
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Boys",
      "Year": 2018,
      "Region": "ACT",
      "Sex": "Boys",
      "Age": "Year 6",
      "Percent": 79.84
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Girls",
      "Year": 2018,
      "Region": "ACT",
      "Sex": "Girls",
      "Age": "Year 6",
      "Percent": 86.3
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Total",
      "Year": 2018,
      "Region": "ACT",
      "Sex": "Total",
      "Age": "Year 6",
      "Percent": 9.99
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Boys",
      "Year": 2018,
      "Region": "ACT",
      "Sex": "Boys",
      "Age": "Year 6",
      "Percent": 8.61
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Girls",
      "Year": 2018,
      "Region": "ACT",
      "Sex": "Girls",
      "Age": "Year 6",
      "Percent": 11.54
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Total",
      "Year": 2009,
      "Region": "ACT",
      "Sex": "Total",
      "Age": "Year 6",
      "Percent": 81.76
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Total",
      "Year": 2012,
      "Region": "ACT",
      "Sex": "Total",
      "Age": "Year 6",
      "Percent": 82.4
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Total",
      "Year": 2015,
      "Region": "ACT",
      "Sex": "Total",
      "Age": "Year 6",
      "Percent": 84.12
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Boys",
      "Year": 2009,
      "Region": "ACT",
      "Sex": "Boys",
      "Age": "Year 6",
      "Percent": 80.4
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Boys",
      "Year": 2012,
      "Region": "ACT",
      "Sex": "Boys",
      "Age": "Year 6",
      "Percent": 81.49
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Boys",
      "Year": 2015,
      "Region": "ACT",
      "Sex": "Boys",
      "Age": "Year 6",
      "Percent": 82.49
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Girls",
      "Year": 2009,
      "Region": "ACT",
      "Sex": "Girls",
      "Age": "Year 6",
      "Percent": 83.06
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Girls",
      "Year": 2012,
      "Region": "ACT",
      "Sex": "Girls",
      "Age": "Year 6",
      "Percent": 83.26
    },
    {
      "Category": "Nutrition",
      "Type": "Fruit",
      "Question": "Fruit consumption (2 serves or more a day)",
      "Question_Sex": "Fruit consumption (2 serves or more a day), Girls",
      "Year": 2015,
      "Region": "ACT",
      "Sex": "Girls",
      "Age": "Year 6",
      "Percent": 85.9
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Total",
      "Year": 2009,
      "Region": "ACT",
      "Sex": "Total",
      "Age": "Year 6",
      "Percent": 13.83
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Total",
      "Year": 2012,
      "Region": "ACT",
      "Sex": "Total",
      "Age": "Year 6",
      "Percent": 13.7
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Total",
      "Year": 2015,
      "Region": "ACT",
      "Sex": "Total",
      "Age": "Year 6",
      "Percent": 9.58
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Boys",
      "Year": 2009,
      "Region": "ACT",
      "Sex": "Boys",
      "Age": "Year 6",
      "Percent": 15.65
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Boys",
      "Year": 2012,
      "Region": "ACT",
      "Sex": "Boys",
      "Age": "Year 6",
      "Percent": 15.4
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Boys",
      "Year": 2015,
      "Region": "ACT",
      "Sex": "Boys",
      "Age": "Year 6",
      "Percent": 9.66
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Girls",
      "Year": 2009,
      "Region": "ACT",
      "Sex": "Girls",
      "Age": "Year 6",
      "Percent": 12.09
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Girls",
      "Year": 2012,
      "Region": "ACT",
      "Sex": "Girls",
      "Age": "Year 6",
      "Percent": 12.1
    },
    {
      "Category": "Nutrition",
      "Type": "Vegetable",
      "Question": "Vegetable consumption (5 serves or more a day)",
      "Question_Sex": "Vegetable consumption (5 serves or more a day), Girls",
      "Year": 2015,
      "Region": "ACT",
      "Sex": "Girls",
      "Age": "Year 6",
      "Percent": 9.5
    }
   ]